import { defineConfig, devices } from '@playwright/test';

// Generated by styleproof-init.
//
// Capture against a PRODUCTION build, never a dev server. Dev servers (`next dev`,
// `vite`, …) JIT-compile each route on first request — slow and TIMING-VARIABLE
// under parallel CI load, so a capture can settle on the loading state on one run and
// the loaded state on the next: phantom diffs and self-check flakes. A built-and-served
// app serves precompiled routes at consistent timing. (StyleProof's settle waits for
// in-flight data either way, but a production build removes the variance at the source.)
export default defineConfig({
  testDir: "./e2e",
  testMatch: "styleproof.spec.ts",
  timeout: 120_000,
  // Capture surfaces in PARALLEL. StyleProof generates one test per surface × width,
  // each an isolated page writing a uniquely-keyed file (`<key>@<width>.json.gz`), with
  // per-page record/replay and frozen clock — so they're independent and safe to run
  // concurrently. Without this, all surfaces sit in one spec file and capture serially;
  // with it they fan out across workers, a near-linear speedup on a multi-surface app.
  // (`--shard` splits them across CI machines too; they write disjoint files into one
  // dir.) Tune `workers` to your machine if needed.
  fullyParallel: true,
  use: {
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
  },
  // Build once, then serve THAT production build for the captures — so you can't
  // accidentally capture a dev server. styleproof-init detected the production
  // serve command from your package scripts/dependencies; tune it here if your
  // framework needs a custom preview command.
  webServer: {
    command: 'npm run build && npm run start',
    url: process.env.BASE_URL || 'http://localhost:3000',
    env: { PORT: '3000' },
    reuseExistingServer: !process.env.CI,
    timeout: 600_000, // a cold production build can take a few minutes
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
});
