import type { Page } from '@playwright/test';
import { defineCrawlCapture } from 'styleproof';

/**
 * styleproof capture spec (generated by `styleproof-init`).
 *
 * Each surface is one deterministic page state. Omit `widths` and StyleProof
 * detects your @media breakpoints from the loaded CSS and sweeps one viewport per
 * band — no config. Capture against a PRODUCTION build — dev servers inject styles.
 *
 *   npx styleproof-map   # capture this commit into the local cache and map store
 *   npx styleproof-diff  # compare cached base/head maps by commit SHA
 */

// StyleProof settles the page for you before it reads — it waits out in-flight data
// and fonts, freezes animations/transitions, and blurs focus. The one thing it can't
// know about is *scroll-reveal* content: elements an IntersectionObserver mounts (or
// fades in) only once they're scrolled into view. settle() triggers that — it scrolls
// the page so those reveals fire, forces common reveal markers to their final state so
// nothing is caught mid-fade, then returns to the top. Tune the selectors to match
// your project. No reveal-on-scroll content? Delete settle() and use the one-liner
// `go: (page) => page.goto('/')`.
async function settle(page: Page) {
  await page.addStyleTag({
    content: `.reveal, [data-reveal], .fade-in, .animate-in {
      opacity: 1 !important;
      transform: none !important;
      visibility: visible !important;
    }`,
  });
  const dimensions = await page.evaluate(() => ({
    scrollHeight: document.body.scrollHeight,
    viewportHeight: Math.max(window.innerHeight, 1),
  }));
  for (let y = 0; y < dimensions.scrollHeight; y += dimensions.viewportHeight) {
    await page.evaluate((scrollY) => window.scrollTo(0, scrollY), y);
    await page.waitForTimeout(60);
  }
  await page.evaluate(() => window.scrollTo(0, 0));
}

// Zero-config capture: crawl every surface your nav links to from '/'. The surface set
// is DISCOVERED from the rendered nav, so it can't drift from it — no hand-listed
// `surfaces` array to maintain, and a page you add to the nav is captured automatically.
// The root (/) is always captured, plus every same-origin <a href> it links to.
defineCrawlCapture({
  from: '/',
  settle, // trigger scroll-reveal per surface (StyleProof handles fonts/animation/network itself)
  // No `widths` → StyleProof detects each surface's @media breakpoints and sweeps one
  // viewport per band. Pass an array (e.g. [1440, 768, 390]) to pin them.
  inventory: true, // also fail the diff when a nav item / route the UI used to offer disappears
  ignore: [], // e.g. ['.live-feed', '.ad-slot'] for nondeterministic regions
  dir: process.env.STYLEMAP_DIR,
  // A single-route SPA whose views are ?tab= / client-routed? Keep only those:
  //   match: /\?tab=/,
  // Turn the crawl into a coverage guard: reconcile the rendered nav against a route
  // registry, both directions — a new linked route with no `expected` entry fails, and
  // an `expected` route the nav stopped linking fails. (Runs inside the capture, so it
  // fires when you capture, not in every test run.) List conditionally-rendered links
  // (auth / feature-flag) in `exclude` so they can't flake the guard either direction:
  //   expected: ['index', 'pricing'],
  //   exclude: { admin: 'feature-flagged, renders only for staff' },
  // Certify menus, dialogs, tabs, and form-error states on every surface as variants:
  //   variants: [{ key: 'menu-open', go: async (page) => { await page.getByRole('button', { name: /menu/i }).click(); } }],
});
