import fs from 'node:fs';
import path from 'node:path';

/** Publish a report folder to the report branch through the GitHub git-data API.
 *
 *  The previous publisher cloned the report branch to add one folder. That made
 *  every publish cost the size of the whole branch: with one `pr-<n>/` folder per
 *  open PR the branch grows without bound, and once it is a few gigabytes the
 *  clone dies mid-transfer and the publish fails on every PR in the repository.
 *  Working through the API instead makes publish cost the size of THIS report:
 *  upload the report blobs, graft them onto the current tip tree server-side,
 *  and fast-forward the ref. No report bytes are ever downloaded.
 *
 *  A blobless (`--filter=blob:none`) clone does not achieve this: `git push`
 *  re-fetches the retained blobs to build its pack, so the transfer cost comes
 *  back at push time. The API path is the only one that stays proportional to
 *  the report. */

export const REPORT_BRANCH_README = `# StyleProof reports

Machine-generated by [styleproof](https://github.com/BenSheridanEdwards/StyleProof).
Each \`pr-<n>/\` holds the latest visual-diff report for that PR — open \`report.md\` to see the before/after crops.
`;

/** Over this many bytes of blobs on the report branch, publish logs a workflow
 *  warning: the branch is drifting toward the size where consumers who still
 *  clone it (checkouts, the scaffolded prune) start to hurt. Publish itself is
 *  size-independent, so this is an early smoke alarm, not a limit. */
export const REPORT_BRANCH_SIZE_WARNING_BYTES = 1_000_000_000;

export type ReportPublishFile = {
  /** Path inside the report folder, for example `report.md` or `crops/hero.png`. */
  relativePath: string;
  content: Buffer;
};

export type ReportPublishRequest = {
  apiBaseUrl: string;
  repository: string;
  token: string;
  branch: string;
  /** Top-level folder for this report, for example `pr-123`. */
  reportPath: string;
  files: ReportPublishFile[];
  commitMessage: string;
  /** Retries for the tip-moved race and for transient API failures. */
  maximumAttempts?: number;
  /** Injection point for tests. Defaults to global fetch. */
  fetchImplementation?: typeof fetch;
  /** Injection point for tests. Defaults to a real sleep. */
  sleepImplementation?: (milliseconds: number) => Promise<void>;
  log?: (line: string) => void;
};

export type ReportPublishResult = {
  commitSha: string;
  /** Total blob bytes on the branch after publish; null when the recursive tree
   *  listing was truncated and the size could not be measured. */
  branchSizeBytes: number | null;
};

class ReportPublishApiError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.status = status;
  }
}

async function realSleep(milliseconds: number): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, milliseconds));
}

function buildClient(request: ReportPublishRequest) {
  const fetchImplementation = request.fetchImplementation ?? fetch;
  const repositoryUrl = `${request.apiBaseUrl}/repos/${request.repository}`;
  async function api<ResponseShape>(method: string, apiPath: string, body?: unknown): Promise<ResponseShape> {
    const response = await fetchImplementation(`${repositoryUrl}${apiPath}`, {
      method,
      headers: {
        authorization: `Bearer ${request.token}`,
        accept: 'application/vnd.github+json',
        ...(body === undefined ? {} : { 'content-type': 'application/json' }),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok) {
      const detail = await response.text().catch(() => '');
      throw new ReportPublishApiError(
        `${method} ${apiPath} -> ${response.status}${detail ? `: ${detail.slice(0, 300)}` : ''}`,
        response.status,
      );
    }
    return (await response.json()) as ResponseShape;
  }
  return { api };
}

type GitTreeEntry = {
  path: string;
  mode: string;
  type: string;
  sha?: string | null;
  size?: number;
};

/** One publish attempt against the current branch tip. Throws
 *  ReportPublishApiError with status 422 when the ref moved under us. */
async function publishOnce(
  request: ReportPublishRequest,
  api: ReturnType<typeof buildClient>['api'],
  log: (line: string) => void,
): Promise<ReportPublishResult> {
  let tipCommitSha: string | null = null;
  try {
    const tipReference = await api<{ object: { sha: string } }>(
      'GET',
      `/git/ref/${encodeURIComponent(`heads/${request.branch}`)}`,
    );
    tipCommitSha = tipReference.object.sha;
  } catch (error) {
    if (!(error instanceof ReportPublishApiError) || error.status !== 404) throw error;
  }

  const blobEntries: GitTreeEntry[] = [];
  for (const file of request.files) {
    const blob = await api<{ sha: string }>('POST', '/git/blobs', {
      content: file.content.toString('base64'),
      encoding: 'base64',
    });
    blobEntries.push({
      path: `${request.reportPath}/${file.relativePath}`,
      mode: '100644',
      type: 'blob',
      sha: blob.sha,
    });
  }

  let treePayload: { base_tree?: string; tree: GitTreeEntry[] };
  if (tipCommitSha === null) {
    // First run: build a self-contained root tree; the branch is created below.
    const readmeBlob = await api<{ sha: string }>('POST', '/git/blobs', {
      content: Buffer.from(REPORT_BRANCH_README).toString('base64'),
      encoding: 'base64',
    });
    treePayload = {
      tree: [{ path: 'README.md', mode: '100644', type: 'blob', sha: readmeBlob.sha }, ...blobEntries],
    };
  } else {
    const tipCommit = await api<{ tree: { sha: string } }>('GET', `/git/commits/${tipCommitSha}`);
    const tipTree = await api<{ tree: GitTreeEntry[] }>('GET', `/git/trees/${tipCommit.tree.sha}`);
    const entries: GitTreeEntry[] = [];
    // Re-publishing replaces the folder wholesale, so a crop deleted from the
    // report does not survive as a stale file. Deleting a path that is not on
    // the tip is an API error, so only delete when the folder exists.
    if (tipTree.tree.some((entry) => entry.type === 'tree' && entry.path === request.reportPath)) {
      entries.push({ path: request.reportPath, mode: '040000', type: 'tree', sha: null });
    }
    if (!tipTree.tree.some((entry) => entry.type === 'blob' && entry.path === 'README.md')) {
      const readmeBlob = await api<{ sha: string }>('POST', '/git/blobs', {
        content: Buffer.from(REPORT_BRANCH_README).toString('base64'),
        encoding: 'base64',
      });
      entries.push({ path: 'README.md', mode: '100644', type: 'blob', sha: readmeBlob.sha });
    }
    treePayload = { base_tree: tipCommit.tree.sha, tree: [...entries, ...blobEntries] };
  }

  const publishedTree = await api<{ sha: string }>('POST', '/git/trees', treePayload);
  const publishedCommit = await api<{ sha: string }>('POST', '/git/commits', {
    message: request.commitMessage,
    tree: publishedTree.sha,
    parents: tipCommitSha === null ? [] : [tipCommitSha],
  });

  if (tipCommitSha === null) {
    // Racing first runs both try to create the ref; the loser gets a 422 and
    // the caller retries against the branch the winner just created.
    await api('POST', '/git/refs', {
      ref: `refs/heads/${request.branch}`,
      sha: publishedCommit.sha,
    });
  } else {
    // force: false keeps this a fast-forward: if another PR's publish advanced
    // the branch since we read the tip, this 422s and the caller retries.
    await api('PATCH', `/git/refs/${encodeURIComponent(`heads/${request.branch}`)}`, {
      sha: publishedCommit.sha,
      force: false,
    });
  }

  let branchSizeBytes: number | null = null;
  try {
    const recursiveTree = await api<{ tree: GitTreeEntry[]; truncated: boolean }>(
      'GET',
      `/git/trees/${publishedTree.sha}?recursive=1`,
    );
    if (!recursiveTree.truncated) {
      branchSizeBytes = recursiveTree.tree
        .filter((entry) => entry.type === 'blob')
        .reduce((total, entry) => total + (entry.size ?? 0), 0);
    }
  } catch {
    // Size telemetry is advisory; never fail a publish over it.
  }
  if (branchSizeBytes !== null && branchSizeBytes > REPORT_BRANCH_SIZE_WARNING_BYTES) {
    log(
      `::warning::StyleProof report branch ${request.branch} holds ${(branchSizeBytes / 1e9).toFixed(2)} GB of reports. Publish does not clone it, but anything that still does is at risk — lower the prune retention or size budget in your styleproof workflow.`,
    );
  }

  return { commitSha: publishedCommit.sha, branchSizeBytes };
}

/** Retry statuses for the ref races publishOnce deliberately surfaces (422 from
 *  a non-fast-forward PATCH or an already-created ref) and for transient API
 *  faults. 4xx client errors other than the race are real failures. */
function isRetryableStatus(status: number): boolean {
  return status === 422 || status === 409 || status >= 500;
}

export async function publishReportFolder(request: ReportPublishRequest): Promise<ReportPublishResult> {
  const { api } = buildClient(request);
  const log = request.log ?? ((line) => process.stderr.write(`${line}\n`));
  const sleep = request.sleepImplementation ?? realSleep;
  const maximumAttempts = request.maximumAttempts ?? 5;
  let lastError: unknown;
  for (let attemptNumber = 1; attemptNumber <= maximumAttempts; attemptNumber += 1) {
    try {
      return await publishOnce(request, api, log);
    } catch (error) {
      lastError = error;
      const retryable = error instanceof ReportPublishApiError ? isRetryableStatus(error.status) : true;
      if (!retryable || attemptNumber === maximumAttempts) throw error;
      log(`report publish attempt ${attemptNumber} failed (${String(error)}); retrying`);
      await sleep(attemptNumber * 2000);
    }
  }
  throw lastError;
}

/** Read the just-published report back at the exact commit we are about to
 *  advertise and require the run receipt. Fail closed: a green run must never
 *  hand out a dead or stale report URL. */
export async function verifyPublishedReceipt(options: {
  apiBaseUrl: string;
  repository: string;
  token: string;
  reportPath: string;
  commitSha: string;
  expectedReceipt: string;
  maximumAttempts?: number;
  fetchImplementation?: typeof fetch;
  sleepImplementation?: (milliseconds: number) => Promise<void>;
}): Promise<void> {
  const fetchImplementation = options.fetchImplementation ?? fetch;
  const sleep = options.sleepImplementation ?? realSleep;
  const maximumAttempts = options.maximumAttempts ?? 5;
  for (let attemptNumber = 1; attemptNumber <= maximumAttempts; attemptNumber += 1) {
    const response = await fetchImplementation(
      `${options.apiBaseUrl}/repos/${options.repository}/contents/${options.reportPath}/report.md?ref=${options.commitSha}`,
      {
        headers: {
          authorization: `Bearer ${options.token}`,
          accept: 'application/vnd.github.raw',
        },
      },
    ).catch(() => null);
    if (response?.ok) {
      const published = await response.text();
      if (published.includes(options.expectedReceipt)) return;
    }
    if (attemptNumber < maximumAttempts) await sleep(attemptNumber * 2000);
  }
  throw new Error(
    `the published report at ${options.reportPath} @ ${options.commitSha} is unreadable or its receipt does not match this run (${options.expectedReceipt}) — do not trust this run's report`,
  );
}

/** Collect exactly what the report step publishes: `report.md` plus every
 *  generated crop it references. Nothing else in the report directory travels. */
export function collectReportFiles(reportDirectory: string): ReportPublishFile[] {
  const files: ReportPublishFile[] = [
    {
      relativePath: 'report.md',
      content: fs.readFileSync(path.join(reportDirectory, 'report.md')),
    },
  ];
  const cropsDirectory = path.join(reportDirectory, 'crops');
  if (fs.existsSync(cropsDirectory)) {
    for (const cropFileName of fs.readdirSync(cropsDirectory).sort()) {
      if (!cropFileName.endsWith('.png')) continue;
      files.push({
        relativePath: `crops/${cropFileName}`,
        content: fs.readFileSync(path.join(cropsDirectory, cropFileName)),
      });
    }
  }
  return files;
}
