// Publish a report folder to the report branch through the GitHub git-data API.
// Cloning the branch to add one folder made every publish cost the size of the
// whole branch (and die once it reached gigabytes); the API path costs the size
// of THIS report: upload the blobs, graft them onto the tip tree server-side,
// fast-forward the ref. No report bytes are ever downloaded.

import fs from 'node:fs';
import path from 'node:path';
import {
  type GitHubApi,
  type GitHubApiOptions,
  type GitTreeEntry,
  advanceBranch,
  createBlob,
  createCommit,
  createTree,
  deleteFolderEntry,
  githubClient,
  logLine,
  readBranchTipCommitSha,
  readCommitTreeSha,
  readTree,
  withRetries,
} from './github-git-data.js';
import { hasDuplicateJsonKeys } from './map-store.js';

const REPORT_BRANCH_README = `# StyleProof reports

Machine-generated by [styleproof](https://github.com/BenSheridanEdwards/StyleProof).
Each \`pr-<n>/\` holds the latest visual-diff report for that PR — open \`report.md\` to see the before/after crops.
`;

/** Above this many blob bytes, publish logs a workflow warning: an early smoke alarm, not a limit. */
export const REPORT_BRANCH_SIZE_WARNING_BYTES = 1_000_000_000;

export type ReportPublishFile = { relativePath: string; content: Buffer };

export type ReportPublishRequest = GitHubApiOptions & {
  branch: string;
  /** Top-level folder for this report, for example `pr-123`. */
  reportPath: string;
  files: ReportPublishFile[];
  commitMessage: string;
};

export type ReportPublishResult = {
  commitSha: string;
  /** Blob bytes on the branch after publish; null when the recursive listing was truncated. */
  branchSizeBytes: number | null;
};

async function readmeEntry(api: GitHubApi): Promise<GitTreeEntry> {
  return { path: 'README.md', mode: '100644', type: 'blob', sha: await createBlob(api, REPORT_BRANCH_README) };
}

/** Replace this PR's stale folder wholesale (only when it exists — deleting an
 *  absent path is an API error) and seed the README if missing. */
async function treeOnTip(api: GitHubApi, request: ReportPublishRequest, tipSha: string, blobs: GitTreeEntry[]) {
  const baseTree = await readCommitTreeSha(api, tipSha);
  const { tree } = await readTree(api, baseTree);
  const entries: GitTreeEntry[] = [];
  if (tree.some((entry) => entry.type === 'tree' && entry.path === request.reportPath)) {
    entries.push(deleteFolderEntry(request.reportPath));
  }
  if (!tree.some((entry) => entry.type === 'blob' && entry.path === 'README.md')) entries.push(await readmeEntry(api));
  return { base_tree: baseTree, tree: [...entries, ...blobs] };
}

async function measureBranchSizeBytes(api: GitHubApi, treeSha: string): Promise<number | null> {
  try {
    const { tree, truncated } = await readTree(api, treeSha, true);
    if (truncated) return null;
    return tree.filter((entry) => entry.type === 'blob').reduce((total, entry) => total + (entry.size ?? 0), 0);
  } catch {
    return null;
  }
}

async function publishOnce(api: GitHubApi, request: ReportPublishRequest): Promise<ReportPublishResult> {
  const log = logLine(request);
  const tipSha = await readBranchTipCommitSha(api, request.branch);
  const blobs: GitTreeEntry[] = [];
  for (const file of request.files) {
    const sha = await createBlob(api, file.content);
    blobs.push({ path: `${request.reportPath}/${file.relativePath}`, mode: '100644', type: 'blob', sha });
  }
  const payload =
    tipSha === null ? { tree: [await readmeEntry(api), ...blobs] } : await treeOnTip(api, request, tipSha, blobs);
  const treeSha = await createTree(api, payload);
  const commitSha = await createCommit(api, request.commitMessage, treeSha, tipSha === null ? [] : [tipSha]);
  await advanceBranch(api, request.branch, tipSha, commitSha);
  const branchSizeBytes = await measureBranchSizeBytes(api, treeSha);
  if (branchSizeBytes !== null && branchSizeBytes > REPORT_BRANCH_SIZE_WARNING_BYTES) {
    log(
      `::warning::StyleProof report branch ${request.branch} holds ${(branchSizeBytes / 1e9).toFixed(2)} GB of reports. Publish does not clone it, but anything that still does is at risk — lower the prune retention or size budget in your styleproof workflow.`,
    );
  }
  return { commitSha, branchSizeBytes };
}

export async function publishReportFolder(request: ReportPublishRequest): Promise<ReportPublishResult> {
  const api = githubClient(request);
  return withRetries(request, 'report publish', () => publishOnce(api, request));
}

type PublishedReceiptOptions = GitHubApiOptions & {
  reportPath: string;
  commitSha: string;
  expectedReceipt: string;
};

async function readPublishedBytes(options: PublishedReceiptOptions, relativePath: string): Promise<Uint8Array | null> {
  const fetchImplementation = options.fetchImplementation ?? fetch;
  const response = await fetchImplementation(
    `${options.apiBaseUrl}/repos/${options.repository}/contents/${options.reportPath}/${relativePath}?ref=${options.commitSha}`,
    { headers: { authorization: `Bearer ${options.token}`, accept: 'application/vnd.github.raw' } },
  ).catch(() => null);
  if (!response?.ok) return null;
  if (typeof response.arrayBuffer === 'function') return new Uint8Array(await response.arrayBuffer());
  return Buffer.from(await response.text(), 'utf8');
}

/** The receipt names this run's head SHA, run id and attempt, so a report published by
 *  any other run fails the read-back; it must appear exactly once, and report.json must
 *  also parse without duplicate keys. */
function receiptMatches(expectedReceipt: string, markdown: Uint8Array | null, report: Uint8Array | null): boolean {
  if (!markdown || !report) return false;
  try {
    const decoder = new TextDecoder('utf-8', { fatal: true });
    const reportSource = decoder.decode(report);
    if (hasDuplicateJsonKeys(reportSource)) return false;
    JSON.parse(reportSource);
    // Exactly one receipt marker, and it is this run's — an extra (injected or stale)
    // marker makes the publication ambiguous, the same rule the approval readback applies.
    const markdownText = decoder.decode(markdown);
    const receiptMarkers = markdownText.split('<!-- styleproof-receipt').length - 1;
    return receiptMarkers === 1 && markdownText.split(expectedReceipt).length - 1 === 1;
  } catch {
    return false;
  }
}

/** Read the just-published report back at the exact commit we are about to advertise. Fails closed. */
export async function verifyPublishedReceipt(options: PublishedReceiptOptions): Promise<void> {
  const sleep = options.sleepImplementation ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
  const maximumAttempts = options.maximumAttempts ?? 5;
  for (let attemptNumber = 1; attemptNumber <= maximumAttempts; attemptNumber += 1) {
    const [markdown, report] = await Promise.all([
      readPublishedBytes(options, 'report.md'),
      readPublishedBytes(options, 'report.json'),
    ]);
    if (receiptMatches(options.expectedReceipt, markdown, report)) return;
    if (attemptNumber < maximumAttempts) await sleep(attemptNumber * 2000);
  }
  throw new Error(
    `the published report at ${options.reportPath} @ ${options.commitSha} is unreadable or its receipt does not match this run (${options.expectedReceipt}) — do not trust this run's report`,
  );
}

/** Exactly what the report step publishes: report.md, report.json, and every generated crop. */
export function collectReportFiles(reportDirectory: string): ReportPublishFile[] {
  const read = (relativePath: string) => ({
    relativePath,
    content: fs.readFileSync(path.join(reportDirectory, relativePath)),
  });
  const files = [read('report.md'), read('report.json')];
  const cropsDirectory = path.join(reportDirectory, 'crops');
  if (fs.existsSync(cropsDirectory)) {
    for (const name of fs.readdirSync(cropsDirectory).sort())
      if (name.endsWith('.png')) files.push(read(`crops/${name}`));
  }
  return files;
}
